apiVersion: syngit.io/v1beta3
kind: RemoteTarget
metadata:
  name: remotetarget-demo-main
spec:
  upstreamRepository: github.com/damsien/test-syngit.git
  upstreamBranch: main
  targetRepository: github.com/damsien/test-syngit.git
  targetBranch: main
  mergeStrategy: TryFastForwardOrHardReset
