apiVersion: syngit.io/v1beta4
kind: RemoteTarget
metadata:
  name: remotetarget-demo-main
spec:
  upstreamRepository: https://github.com/damsien/test-syngit.git
  upstreamBranch: main
  targetRepository: https://github.com/damsien/test-syngit.git
  targetBranch: main
