apiVersion: syngit.io/v1beta3
kind: RemoteSyncer
metadata:
  name: capi-cluster-create-update-delete
  annotations:
    syngit.io/remotetarget.pattern.one-or-many-branches: main
spec:
  remoteRepository: <YOUR_REPOSITORY_URL>.git
  defaultBranch: main
  strategy: CommitApply
  targetStrategy: OneTarget
  bypassInterceptionSubjects:
  - kind: ServiceAccount
    name: system:serviceaccount:argocd:argocd-application-controller
    namespace: argocd
  - kind: ServiceAccount
    name: system:serviceaccount:argocd:argocd-server
    namespace: argocd
  - kind: ServiceAccount
    name: system:serviceaccount:capi-system:capi-manager
    namespace: capi-system
  defaultUnauthorizedUserMode: Block
  rootPath: capi
  excludedFields:
    - spec.controlPlaneEndpoint.host
    - spec.controlPlaneEndpoint.port
  scopedResources:
    rules:
    - apiGroups: ["cluster.x-k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["clusters"]
      operations: ["CREATE", "UPDATE","DELETE"]