---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-basic-auth-git
type: kubernetes.io/basic-auth
stringData:
  username: <YOUR_GIT_USERNAME>
  password: <YOUR_GIT_PERSONAL_ACCESS_TOKEN>
---
apiVersion: syngit.io/v1beta3
kind: RemoteUser
metadata:
  name: my-remoteuser
  annotations:
    syngit.io/remoteuserbinding.managed: "true"
spec:
  gitBaseDomainFQDN: <GIT_FQDN>
  email: <YOUR_EMAIL>
  secretRef:
    name: my-secret-basic-auth-git