# kind-cluster-with-extramounts.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
  image: kindest/node:v1.31.0
#   extraPortMappings:
#     - containerPort: 80
#       hostPort: 80
#     - containerPort: 443
#       hostPort: 443
# - role: worker
#   image: kindest/node:v1.31.0