apiVersion: syngit.io/v1beta4
kind: RemoteSyncer
metadata:
  name: deployment-create-update-delete
  annotations:
  
    syngit.io/remotetarget.pattern.one-or-many-branches: main
    # syngit.io/remotetarget.pattern.user-specific: one-user-one-branch
spec:

  scopedResources:
    rules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments"]
      operations: ["CREATE", "UPDATE","DELETE"]


  remoteRepository: <YOUR_REPO>
  defaultBranch: main


  strategy: CommitApply
  targetStrategy: MultipleTarget


  bypassInterceptionSubjects:
  - kind: ServiceAccount
    name: system:serviceaccount:argocd:argocd-application-controller
    namespace: argocd
  - kind: ServiceAccount
    name: system:serviceaccount:argocd:argocd-server
    namespace: argocd
  defaultUnauthorizedUserMode: Block

  
  excludedFields:
    - metadata.annotations
    - spec.progressDeadlineSeconds
    - spec.revisionHistoryLimit
    - spec.strategy
    - spec.template.spec.dnsPolicy
    - spec.template.spec.restartPolicy
    - spec.template.spec.schedulerName
    - spec.template.spec.securityContext
    - spec.template.spec.terminationGracePeriodSeconds
    - spec.template.spec[0].terminationMessagePath
    - spec.template.spec[0].terminationMessagePolicy
    - spec.template.spec[0].resources