apiVersion: syngit.io/v1beta4
kind: RemoteSyncer
metadata:
  name: capi-cluster-create-update-delete
  annotations:
  
    syngit.io/remotetarget.pattern.one-or-many-branches: main
    syngit.io/remotetarget.pattern.user-specific: one-user-one-branch
spec:


  remoteRepository: https://github.com/damsien/test-syngit.git
  defaultBranch: main


  strategy: CommitApply
  targetStrategy: MultipleTarget


  scopedResources:
    rules:
    - apiGroups: ["cluster.x-k8s.io"]
      apiVersions: ["v1beta1"]
      resources: ["clusters"]
      operations: ["CREATE", "UPDATE","DELETE"]


  defaultUnauthorizedUserMode: Block
  rootPath: capi
  excludedFields:
    - metadata.finalizers
    - spec.controlPlaneEndpoint
    - spec.controlPlaneRef
    - spec.infrastructureRef


  bypassInterceptionSubjects:
  - kind: ServiceAccount
    name: system:serviceaccount:argocd:argocd-application-controller
    namespace: argocd
  - kind: ServiceAccount
    name: system:serviceaccount:argocd:argocd-server
    namespace: argocd
  - kind: ServiceAccount
    name: system:serviceaccount:capi-system:capi-manager
    namespace: capi-system